# Generated by Django 5.1.1 on 2024-09-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='bid_step',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='auction',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
